// Translation Dictionary for SHIELD Smart Tourist Safety System
// Supports English + 10 Indian Languages

const TRANSLATIONS = {
  en: {
    appName: "SHIELD Mobile Safety",
    safetyScore: "Safety Score",
    panicSOS: "EMERGENCY PANIC SOS",
    gpsStatus: "Live GPS Tracking",
    gpsActive: "GPS Active & Shared",
    gpsInactive: "GPS Paired (Offline)",
    iotVitals: "IoT Smart Band Vitals",
    heartRate: "Heart Rate",
    oxygen: "Oxygen (SpO2)",
    bandBattery: "Band Battery",
    geofenceAlert: "Restricted Zone Alert",
    statusSafe: "SAFE STATUS",
    statusWarning: "WARNING STATE",
    statusSOS: "DISTRESS TRIGGERED",
    batteryWarning: "Battery Low! Connect to Power.",
    kycVerified: "KYC VERIFIED",
    blockchainSecured: "Secured by Consortium Ledger",
    itineraryValid: "Itinerary Active",
    panicActive: "DISTRESS BEACON BROADCASTING",
    privacyNotice: "Data is end-to-end encrypted and blockchain registered. Location sharing is opt-in and restricted to authorized safety teams.",
    optInTracker: "Share Location with Police",
    langSelect: "Select Language",
    restrictedZoneTitle: "WARNING: RESTRICTED ZONE!",
    restrictedZoneDesc: "You have entered a high-sensitivity forest reserve/border zone. Law enforcement has been notified. Please return immediately.",
    missingSignal: "Signal Loss Risk High",
    normalHealth: "IoT Vitals Normal",
    healthAnomaly: "CRITICAL: Vital Anomaly Detected!",
  },
  hi: { // Hindi
    appName: "शील्ड मोबाइल सुरक्षा",
    safetyScore: "सुरक्षा स्कोर",
    panicSOS: "आपातकालीन पैनिक SOS",
    gpsStatus: "लाइव जीपीएस ट्रैकिंग",
    gpsActive: "जीपीएस सक्रिय और साझा",
    gpsInactive: "जीपीएस कनेक्टेड (ऑफ़लाइन)",
    iotVitals: "आईओटी स्मार्ट बैंड वाइटल्स",
    heartRate: "हृदय गति",
    oxygen: "ऑक्सीजन (SpO2)",
    bandBattery: "बैंड बैटरी",
    geofenceAlert: "प्रतिबंधित क्षेत्र चेतावनी",
    statusSafe: "सुरक्षित स्थिति",
    statusWarning: "चेतावनी की स्थिति",
    statusSOS: "संकट सक्रिय",
    batteryWarning: "बैटरी कम है! चार्जर कनेक्ट करें।",
    kycVerified: "केवाईसी सत्यापित",
    blockchainSecured: "कंसोर्टियम लेजर द्वारा सुरक्षित",
    itineraryValid: "यात्रा कार्यक्रम सक्रिय",
    panicActive: "संकट संकेत प्रसारित हो रहा है",
    privacyNotice: "डेटा एंड-टू-एंड एन्क्रिप्टेड और ब्लॉकचेन पंजीकृत है। स्थान साझाकरण वैकल्पिक है और केवल अधिकृत सुरक्षा टीमों तक सीमित है।",
    optInTracker: "पुलिस के साथ स्थान साझा करें",
    langSelect: "भाषा चुनें",
    restrictedZoneTitle: "चेतावनी: प्रतिबंधित क्षेत्र!",
    restrictedZoneDesc: "आपने एक उच्च-संवेदनशील वन आरक्षित/सीमा क्षेत्र में प्रवेश किया है। पुलिस को सूचित कर दिया गया है। कृपया तुरंत वापस लौटें।",
    missingSignal: "सिग्नल हानि का जोखिम उच्च",
    normalHealth: "आईओटी वाइटल्स सामान्य",
    healthAnomaly: "गंभीर: वाइटल्स विसंगति पाई गई!",
  },
  bn: { // Bengali
    appName: "শিল্ড মোবাইল সুরক্ষা",
    safetyScore: "সুরক্ষা স্কোর",
    panicSOS: "জরুরী প্যানিক SOS",
    gpsStatus: "লাইভ জিপিএস ট্র্যাকিং",
    gpsActive: "জিপিএস সক্রিয় ও শেয়ার্ড",
    gpsInactive: "জিপিএস অফলাইন",
    iotVitals: "আইওটি স্মার্ট ব্যান্ড ভাইটালস",
    heartRate: "হৃদস্পন্দন হার",
    oxygen: "অক্সিজেন মাত্রা (SpO2)",
    bandBattery: "ব্যান্ড ব্যাটারি",
    geofenceAlert: "নিষিদ্ধ এলাকা সতর্কতা",
    statusSafe: "নিরাপদ অবস্থা",
    statusWarning: "সতর্কতা অবস্থা",
    statusSOS: "বিপদ সংকেত সক্রিয়",
    batteryWarning: "ব্যাটারি কম! চার্জার যুক্ত করুন।",
    kycVerified: "কেওয়াইসি যাচাইকৃত",
    blockchainSecured: "কনসোর্টিয়াম লেজার দ্বারা সুরক্ষিত",
    itineraryValid: "ভ্রমণসূচী সক্রিয়",
    panicActive: "বিপদ সংকেত পাঠানো হচ্ছে",
    privacyNotice: "ডেটা এন্ড-টু-এন্ড এনক্রিপ্ট করা এবং ব্লকচেইন নিবন্ধিত। অবস্থান ভাগ করা ঐচ্ছিক এবং শুধুমাত্র অনুমোদিত নিরাপত্তা টিমের মধ্যে সীমাবদ্ধ।",
    optInTracker: "পুলিশের সাথে অবস্থান শেয়ার করুন",
    langSelect: "ভাষা নির্বাচন করুন",
    restrictedZoneTitle: "সতর্কতা: নিষিদ্ধ এলাকা!",
    restrictedZoneDesc: "আপনি একটি উচ্চ-সংবেদনশীল বন সংরক্ষণ/সীমান্ত এলাকায় প্রবেশ করেছেন। পুলিশকে জানানো হয়েছে। অনুগ্রহ করে অবিলম্বে ফিরে যান।",
    missingSignal: "সংকেত হারানোর ঝুঁকি বেশি",
    normalHealth: "আইওটি ভাইটালস স্বাভাবিক",
    healthAnomaly: "গুরুতর: ভাইটালস অসঙ্গতি চিহ্নিত!",
  },
  as: { // Assamese
    appName: "শ্বিল্ড ম’বাইল সুৰক্ষা",
    safetyScore: "সুৰক্ষা স্ক’ৰ",
    panicSOS: "জৰুৰীকালীন পেনিক SOS",
    gpsStatus: "লাইভ জিপিএছ ট্ৰেকিং",
    gpsActive: "জিপিএছ সক্ৰিয় আৰু শ্বেয়াৰ্ড",
    gpsInactive: "জিপিএছ অফলাইন",
    iotVitals: "আইঅ’টি স্মাৰ্ট বেণ্ড ভাইটেলচ",
    heartRate: "হৃদস্পন্দন",
    oxygen: "অক্সিজেন (SpO2)",
    bandBattery: "বেণ্ড বেটাৰী",
    geofenceAlert: "নিষিদ্ধ এলেকা সতৰ্কতা",
    statusSafe: "সুৰক্ষিত অৱস্থা",
    statusWarning: "সতৰ্কতা অৱস্থা",
    statusSOS: "বিপদ সক্ৰিয়",
    batteryWarning: "বেটাৰী কম! সোনকালে চাৰ্জ কৰক।",
    kycVerified: "কেৱাইচি প্ৰমাণিত",
    blockchainSecured: "ব্লকচেইন লেজাৰ দ্বাৰা সুৰক্ষিত",
    itineraryValid: "ভ্ৰমণসূচী সক্ৰিয়",
    panicActive: "বিপদ সংকেত প্ৰচাৰ কৰা হৈছে",
    privacyNotice: "তথ্য এন্ড-টু-এন্ড এনক্ৰিপ্ট কৰা আৰু ব্লকচেইন পঞ্জীভুক্ত। অৱস্থান শ্বেয়াৰ কৰাটো ঐচ্ছিক আৰু কেৱল সুৰক্ষা দলৰ বাবে সীমিত।",
    optInTracker: "আৰক্ষীৰ সৈতে অৱস্থান শ্বেয়াৰ কৰক",
    langSelect: "ভাষা বাছনি কৰক",
    restrictedZoneTitle: "সতৰ্কতা: নিষিদ্ধ এলেকা!",
    restrictedZoneDesc: "আপুনি অতি সংবেদনশীল বনাঞ্চল বা সীমান্ত অঞ্চলত প্ৰৱেশ কৰিছে। আৰক্ষীক জনোৱা হৈছে। অনুগ্ৰহ কৰি লগে লগে ঘূৰি আহক।",
    missingSignal: "সংকেত হেৰুওৱাৰ আশংকা বেছি",
    normalHealth: "আইঅ’টি ভাইটেলচ স্বাভাৱিক",
    healthAnomaly: "গুৰুতৰ: ভাইটেলচ অস্বাভাৱিক ৰূপ ধৰা পৰিছে!",
  },
  mni: { // Manipuri
    appName: "শীল্ড মোবাইল সেফটি",
    safetyScore: "সেফটি স্কোর",
    panicSOS: "ইমার্জেন্সী পেনিক SOS",
    gpsStatus: "লাইভ জিপিএস ট্রেকিং",
    gpsActive: "জিপিএস এক্টিভ ওইরে",
    gpsInactive: "জিপিএস ওফলাইন",
    iotVitals: "আইওটি স্মার্ত ব্যান্ড ভাইতেল্স",
    heartRate: "হকার থাঙবা",
    oxygen: "ওক্সিজেন (SpO2)",
    bandBattery: "ব্যান্ড বেত্তরী",
    geofenceAlert: "অথিংবা মফম চেকশিন চেকপা",
    statusSafe: "শেফ ওইবা ফিভম",
    statusWarning: "চেকশিন চেকপা ফিভম",
    statusSOS: "অকি-অখুন্নং লৈরে",
    batteryWarning: "বেত্তরী লৈত্রে! চার্জ তৌবীয়ু।",
    kycVerified: "কেওয়াইসি ভেরিফাই তৌরে",
    blockchainSecured: "ব্লকচেন লেজরনা শেমজিলবা",
    itineraryValid: "চৎকদবা খোঙচৎ এক্টিভ লৈরে",
    panicActive: "ইমার্জেন্সী সিগনেল থাদোরে",
    privacyNotice: "দেতা খুদিংমক এনক্রিপ্ট তৌরে অমসুং ব্লকচেনদা রেজিস্তর তৌরে। মফম লান্থোকপা অসি মশানা পামজবা খক্তনি অমসুং সেফটি তিমখক্তনা উবা ফংগনি।",
    optInTracker: "পুলিশকা মফম লান্থোকপা শিয়র তৌবা",
    langSelect: "লোল খনবীয়ু",
    restrictedZoneTitle: "চেকশিন: অথিংবা মফম!",
    restrictedZoneDesc: "নহা অতি সংবেদনশীল উমং নত্রগা ঙমখৈ মফমদা চঙলে। পুলিশতা খঙহনখ্রে। দয়া চানি অথুবদা হল্লকউ।",
    missingSignal: "সিগনেল মাঙবগী অকিবা লৈ",
    normalHealth: "আইওটি ভাইতেল্স নরমেল ওই",
    healthAnomaly: "অকিবা: ভাইতেল্স অহোংবা উরে!",
  },
  kha: { // Khasi
    appName: "SHIELD Jingiada Mobile",
    safetyScore: "Jingshngain",
    panicSOS: "SOS JINGKYRDUH PANIC",
    gpsStatus: "Buh Dak GPS Live",
    gpsActive: "Kyntiew GPS & Sam",
    gpsInactive: "GPS Offline",
    iotVitals: "IoT Smart Band Vitals",
    heartRate: "Jingduriñ Mynsiem",
    oxygen: "Lyer Oxygen (SpO2)",
    bandBattery: "Battery Wait",
    geofenceAlert: "Kylliang Shnong ba Khang",
    statusSafe: "Kynjah Shngain",
    statusWarning: "Maham Danger",
    statusSOS: "Kynrum Kynram SOS",
    batteryWarning: "Duna Battery! Bsa Ding.",
    kycVerified: "Verify KYC",
    blockchainSecured: "Pynskhem da Blockchain Ledger",
    itineraryValid: "Ka Itinerary Active",
    panicActive: "Pynphriang Khor SOS",
    privacyNotice: "Ki jingtip ki long ba la da da ka encryption bad register ha ka Blockchain. Sam jaka long tang lada mon bad tang na ka bynta ki team jingshngain.",
    optInTracker: "Sam Jaka bad ki Pulit",
    langSelect: "Jied Ktien",
    restrictedZoneTitle: "WARNING: JAKA BA LA KHANG!",
    restrictedZoneDesc: "Pih phi la rung ha ka khlaw ba la da lane jaka khappud. La pyntip ia ki pulit. Sngewbha wanphai kloi.",
    missingSignal: "Ma ban duh signal",
    normalHealth: "Normal Vitals",
    healthAnomaly: "CAUTION: Kylla Ki Vitals!",
  },
  miz: { // Mizo
    appName: "SHIELD Hlimna Him",
    safetyScore: "Himna Mark",
    panicSOS: "HMANGAIH SOS PANIC",
    gpsStatus: "GPS Hmun Hmuh",
    gpsActive: "GPS Him/Hman A Ni",
    gpsInactive: "GPS Chhia",
    iotVitals: "IoT Smart Band Vitals",
    heartRate: "Phu Hmun",
    oxygen: "Oxygen Level (SpO2)",
    bandBattery: "Band Battery",
    geofenceAlert: "Ram Khap Himna Maham",
    statusSafe: "A HIM E",
    statusWarning: "FIMKHUR RAWH",
    statusSOS: "BUAI TAWP KHOK",
    batteryWarning: "Battery a tlem! Charge vat rawh.",
    kycVerified: "KYC Fimkhur Him",
    blockchainSecured: "Blockchain hmanga him tlat",
    itineraryValid: "Itinerary Active",
    panicActive: "SOS signal a kal mek",
    privacyNotice: "I data zawng zawng hi thuruk tlat leh Blockchain-a ziah luh a ni. I awmna hmun in-share hi i duhthlanna a ni a, safety team chauhvin an hmu thei.",
    optInTracker: "Police hnenah i hmun share rawh",
    langSelect: "Tawng thlang rawh",
    restrictedZoneTitle: "FIMKHUR: RAM KHAP CHHUNG!",
    restrictedZoneDesc: "Ram hnuai khap hmun emaw border zone-ah i lut mek. Police-te hrilh an ni tawh. A rang lamin chhuak leh rawh.",
    missingSignal: "Signal chhiat a hlauhawm",
    normalHealth: "IoT vitals a tha",
    healthAnomaly: "HIM LO: Vitals dik lo a awm!",
  },
  bod: { // Bodo
    appName: "शील्ड मोबाइल रैखाथि",
    safetyScore: "रैखाथि नम्बर",
    panicSOS: "जोगनां पैनिक SOS",
    gpsStatus: "लाइभ जिपिएस ट्रैकिं",
    gpsActive: "जिपिएस एक्टिभ आरो सेयार",
    gpsInactive: "जिपिएस अफलाइन",
    iotVitals: "आईओटी स्मार्ट बेंड वाइटल्स",
    heartRate: "मेलाय दावबायनाय",
    oxygen: "अक्सिजेन (SpO2)",
    bandBattery: "बेंड बेटरी",
    geofenceAlert: "हेंथा गोनां ओनसोल सांग्रांथि",
    statusSafe: "रैखाथि थासारि",
    statusWarning: "सांग्रां थासारि",
    statusSOS: "जोगनां खहा",
    batteryWarning: "बेटरी खम जाबाय! चार्ज खालाम।",
    kycVerified: "केवाईसी भेरिफाइड",
    blockchainSecured: "ब्लकचेन लेजारजों रैखाथि गोनां",
    itineraryValid: "थांखिनाय फारिलाइ एक्टिभ",
    panicActive: "खहा सोदोब दैथाय हरगासिनो दं",
    privacyNotice: "डेटाया एनक्रिप्टेड आरो ब्लकचेनआव रजिस्टार खालामनाय। थासारि सेयार खालामनाया गावनि खुसि आरो रैखाथि हानजाजों सिमागोनां।",
    optInTracker: "पुलिसनो थासारि खौरां हर",
    langSelect: "राव बाछाय",
    restrictedZoneTitle: "सांग्रांथि: हेंथा गोनां ओनसोल!",
    restrictedZoneDesc: "नोंथाङा सांग्रांथि हाग्रामा बा सिमा ओनसोलआव हाबबाय। पुलिसनो खौरां हरबाय। अननानै गोख्रैनो गिदिंफिन।",
    missingSignal: "सिगनेल गोमानायनि गिनाय दं",
    normalHealth: "वाइटल्स मोजां",
    healthAnomaly: "गोनां: वाइटल्स गोरोन्थि नुजाबाय!",
  },
  nep: { // Nepali
    appName: "शील्ड मोबाइल सुरक्षा",
    safetyScore: "सुरक्षा स्कोर",
    panicSOS: "आकस्मिक प्यानिक SOS",
    gpsStatus: "लाइभ जीपीएस ट्र्याकिङ",
    gpsActive: "जीपीएस सक्रिय र साझा",
    gpsInactive: "जीपीएस अफलाइन",
    iotVitals: "आईओटी स्मार्ट ब्यान्ड भाइटल्स",
    heartRate: "मुटुको गति",
    oxygen: "अक्सिजन (SpO2)",
    bandBattery: "ब्यान्ड ब्याट्री",
    geofenceAlert: "प्रतिबन्धित क्षेत्र चेतावनी",
    statusSafe: "सुरक्षित अवस्था",
    statusWarning: "सचेत अवस्था",
    statusSOS: "सङ्कट उत्पन्न",
    batteryWarning: "ब्याट्री कम छ! चार्ज गर्नुहोस्।",
    kycVerified: "केवाईसी प्रमाणित",
    blockchainSecured: "कन्सोर्टियम लेजरद्वारा सुरक्षित",
    itineraryValid: "यात्रा विवरण सक्रिय",
    panicActive: "सङ्कट सङ्केत प्रसारित भइरहेको छ",
    privacyNotice: "डाटा पूर्ण रूपमा सुरक्षित र ब्लकचेनमा दर्ता छ। स्थान साझा गर्नु ऐच्छिक हो र केवल आधिकारिक सुरक्षा टोलीहरूको पहुँचमा हुन्छ।",
    optInTracker: "प्रहरीसँग स्थान साझा गर्नुहोस्",
    langSelect: "भाषा छान्नुहोस्",
    restrictedZoneTitle: "चेतावनी: प्रतिबन्धित क्षेत्र!",
    restrictedZoneDesc: "तपाईं संवेदनशील वन क्षेत्र वा सीमा क्षेत्रमा प्रवेश गर्नुभएको छ। प्रहरीलाई सूचित गरिएको छ। कृपया तुरुन्तै फर्कनुहोस्।",
    missingSignal: "सिङ्नल हराउने उच्च जोखिम",
    normalHealth: "भाइटल्स सामान्य छ",
    healthAnomaly: "गम्भीर: भाइटल्समा गडबडी देखियो!",
  },
  or: { // Odia
    appName: "ସିଲ୍ଡ ମୋବାଇଲ ସୁରକ୍ଷା",
    safetyScore: "ସୁରକ୍ଷା ସ୍କୋର",
    panicSOS: "ଜରୁରୀକାଳୀନ ପ୍ୟାନିକ SOS",
    gpsStatus: "ଲାଇଭ ଜିପିଏସ ଟ୍ରାକିଂ",
    gpsActive: "ଜିପିଏସ ସକ୍ରିୟ ଓ ଶେୟାର୍ଡ",
    gpsInactive: "ଜିପିଏସ ଅଫଲାଇନ",
    iotVitals: "ଆଇଓଟି ସ୍ମାର୍ଟ ବ୍ୟାଣ୍ଡ ଭାଇଟାଲ୍ସ",
    heartRate: "ହୃଦସ୍ପନ୍ଦନ",
    oxygen: "ଅମ୍ଳଜାନ (SpO2)",
    bandBattery: "ବ୍ୟାଣ୍ଡ ବ୍ୟାଟେରୀ",
    geofenceAlert: "ନିଷିଦ୍ଧାଞ୍ଚଳ ସତର୍କତା",
    statusSafe: "ସୁରକ୍ଷିତ ସ୍ଥିତି",
    statusWarning: "ସତର୍କ ସ୍ଥିତି",
    statusSOS: "ବିପଦ ସକ୍ରିୟ",
    batteryWarning: "ବ୍ୟାଟେରୀ କମ ଅଛି! ଚାର୍ଜ କରନ୍ତୁ।",
    kycVerified: "କେୱାଇସି ଯାଞ୍ଚ ସଫଳ",
    blockchainSecured: "ବ୍ଲକଚେନ ଲେଜର ଦ୍ୱାରା ସୁରକ୍ଷିତ",
    itineraryValid: "ଯାତ୍ରା ସୂଚୀ ସକ୍ରିୟ",
    panicActive: "ବିପଦ ସଙ୍କେତ ପ୍ରସାରିତ ହେଉଛି",
    privacyNotice: "ତଥ୍ୟ ସମ୍ପୂର୍ଣ୍ଣ ସୁରକ୍ଷିତ ଏବଂ ବ୍ଲକଚେନରେ ପଞ୍ଜୀକୃତ। ସ୍ଥାନ ସହଭାଗିତା ଇଚ୍ଛାଧୀନ ଏବଂ କେବଳ ସୁରକ୍ଷା ବାହିନୀ ପାଇଁ ସୀମିତ।",
    optInTracker: "ପୋଲିସ ସହ ସ୍ଥାନ ସେୟାର କରନ୍ତୁ",
    langSelect: "ଭାଷା ଚୟନ କରନ୍ତୁ",
    restrictedZoneTitle: "ସତର୍କତା: ନିଷିଦ୍ଧାଞ୍ଚଳ!",
    restrictedZoneDesc: "ଆପଣ ଏକ ସମ୍ବେଦନଶୀଳ ଜଙ୍ଗଲ କିମ୍ବା ସୀମାନ୍ତ ଅଞ୍ଚଳରେ ପ୍ରବେଶ କରିଛନ୍ତି। ପୋଲିସକୁ ଜଣାଇ ଦିଆଯାଇଛି। ଦୟାକରି ତୁରନ୍ତ ଫେରିଆସନ୍ତୁ।",
    missingSignal: "ସିଗନାଲ ହରାଇବାର ଆଶଙ୍କା ଅଧିକ",
    normalHealth: "ଭାଇଟାଲ୍ସ ସ୍ୱାଭାବିକ ଅଛି",
    healthAnomaly: "ଗୁରୁତର: ଭାଇଟାଲ୍ସରେ ଅସଙ୍ଗତି ମିଳିଲା!",
  },
  te: { // Telugu
    appName: "షీల్డ్ మొబైల్ సేఫ్టీ",
    safetyScore: "రక్షణ స్కోరు",
    panicSOS: "అత్యవసర పానిక్ SOS",
    gpsStatus: "లైవ్ జీపీఎస్ ట్రాకింగ్",
    gpsActive: "జీపీఎస్ యాక్టివ్ & షేర్డ్",
    gpsInactive: "జీపీఎస్ ఆఫ్లైన్",
    iotVitals: "ఐఓటీ స్మార్ట్ బ్యాండ్ వైటల్స్",
    heartRate: "గుండె వేగం",
    oxygen: "ఆక్సిజన్ లెవెల్ (SpO2)",
    bandBattery: "బ్యాండ్ బ్యాటరీ",
    geofenceAlert: "నిషిద్ధ ప్రాంత హెచ్చరిక",
    statusSafe: "సురక్షిత స్థితి",
    statusWarning: "హెచ్చరిక స్థితి",
    statusSOS: "విపత్తు యాక్టివ్",
    batteryWarning: "బ్యాటరీ తక్కువగా ఉంది! ఛార్జర్ కనెక్ట్ చేయండి.",
    kycVerified: "కేవైసీ వెరిఫైడ్",
    blockchainSecured: "బ్లాక్‌చైన్ కన్సార్టియం ద్వారా సురక్షితం",
    itineraryValid: "ప్రయాణ ప్రణాళిక యాక్టివ్",
    panicActive: "అత్యవసర సంకేతం ప్రసారం చేయబడుతోంది",
    privacyNotice: "డేటా పూర్తిగా ఎన్క్రిప్ట్ చేయబడింది మరియు బ్లాక్‌చైన్‌లో నమోదైంది. లొకేషన్ షేరింగ్ అనేది ఐచ్ఛికం మరియు కేవలం భద్రతా దళాలకు మాత్రమే అందుబాటులో ఉంటుంది.",
    optInTracker: "పోలీసులతో లొకేషన్ షేర్ చేయండి",
    langSelect: "భాషను ఎంచుకోండి",
    restrictedZoneTitle: "హెచ్చరిక: నిషిద్ధ ప్రాంతం!",
    restrictedZoneDesc: "మీరు అత్యంత సున్నితమైన అడవి/సరిహద్దు ప్రాంతంలోకి ప్రవేశించారు. పోలీసులకు సమాచారం అందించాము. దయచేసి వెంటనే వెనక్కి వెళ్ళండి.",
    missingSignal: "సిగ్నల్ కోల్పోయే ప్రమాదం ఎక్కువ",
    normalHealth: "వైటల్స్ సాధారణంగా ఉన్నాయి",
    healthAnomaly: "తీవ్రమైనది: వైటల్స్‌లో తేడా కనుగొనబడింది!",
  }
};

// Export to window object for global availability
window.TRANSLATIONS = TRANSLATIONS;
